language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: accn-js-env-class-presentation
  on:
    repo: jr-araque/accenture-js-env-class